local: &local
    build: .
    container_name: fileserver
    ports:
        - 5000:5000
    volumes:
        - .:/app
        - ./vendor:/usr/api/vendor
    environment:
        PYTHONPATH: /app
        PYTHONUSERBASE: /usr/api/vendor
        ARTIFACTS_PATH: /app/data
